spring:
  profiles: development
server:
  port: 8081
bootrest:
  customerproperty: 10X development

security:
  user:
    name: guest
    password: guest123

  oauth2:
    client:
      clientId: trustedclient
      clientSecret: trustedclient123
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
---
spring:
  profiles: production

server:
  port: 9090

bootrest:
  customerproperty: 10X production

security:
  user:
    name: guest
    password: guest123

  oauth2:
    client:
      clientId: trustedclient
      clientSecret: trustedclient123
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
