spring:
  profiles: development
server:
  port: 8081
bootrest:
  customerproperty: 10X development
---
spring:
  profiles: production

server:
  port: 9090

bootrest:
  customerproperty: 10X production
